---
title: "R Leslie Matrix Example"
author: "Grace Lewin"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Creating matrices in R

Use the `matrix()` function to wrap a series of values (a vector) into a matrix.

- Use `nrow = ` to specify number of rows
- Use `ncol = ` to specify number of columns
- Use `byrow = TRUE` to populate the matrix by ROWS instead of columns 

```{r}
cats <- c(1, 3, 6, 5, 7, 3, 2, 1, 9, 5, 4, 3, 11, 300)

# Wrap cats into a matrix
cat_matrix <- matrix(data = cats, nrow = 4, ncol = 5, byrow = TRUE)
```

```{r}
dogs <- matrix(data = c(1, 0, 2, 3), nrow = 2, ncol = 2, byrow = TRUE)
parrots <- matrix(data = c(4, 6, 10, 3), nrow = 2, ncol = 2, byrow = TRUE)

dogs + parrots

dogs - parrots

4*dogs

# to multiply matrices together, you have to use the DOT PRODUCT
dogs %*% parrots

```

## Leslie Matrix

Make projection matrix
```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0.6), nrow = 3, ncol = 3, byrow = TRUE)

# Specify the initial conditions
# What is the population in each life stage at year 0?

insect_y0 <- c(12000, 700, 500)

insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# Project the poulation at each life stage for years 2, 3, and 4

insect_y2 <- insect_leslie %*% insect_y1
insect_y2
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
insect_y4 <- insect_leslie %*% insect_y3
insect_y4
```


